version: '3.4'
services:
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    restart: always
    build:
      context: .
      dockerfile: backend/db/Dockerfile
    environment:
      TZ: America/Sao_Paulo
      SA_PASSWORD: "!aA12345"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    networks:
      - despesas-network

  backend:
    image: mcr.microsoft.com/dotnet/aspnet:6.0-focal
    build: 
      context: .
      dockerfile: ./backend/Dockerfile
    environment:
      TZ: America/Sao_Paulo
      ASPNETCORE_ENVIRONMENT: Development
    ports:
      - "5001:5001"      
      - "5202:5202"
    depends_on:
      - db
    networks:
      - despesas-network

  frontend:  
    image: node:lts-alpine
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    environment:
      TZ: America/Sao_Paulo
      NODE_ENV: Production
    ports:
      - "3000:3000"      
    depends_on:
      - backend
    networks:
      - despesas-network
networks:
    despesas-network:
        driver: bridge