# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  backenddespesasinteligente:
    image: backenddespesasinteligente
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 3001:3001
      - 3000:3000
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
