version: '3.8'

services:
  db:
    container_name: mysql-server-in-docker
    image: mysql-db
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile-local
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: "!aA12345"
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      MYSQL_DATABASE: DespesasPessoaisDB
    ports:
      - "3308:3306"
    networks:
      - despesas-network

networks:
    despesas-network:
        driver: bridge